FROM ros:melodic-perception

# Create a Catkin workspace
RUN apt-get update && \
    apt-get install -y python-catkin-tools
RUN mkdir -p /root/catkin_ws/src
WORKDIR /root/catkin_ws
RUN bash -c "source /opt/ros/melodic/setup.bash && \
             catkin init && \
             catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release"

# Download sources
RUN git clone https://github.com/srv/viso2.git
RUN git clone https://github.com/ActiveIntelligentSystemsLab/ros_optical_flow.git src/ros_optical_flow
RUN git clone https://github.com/ActiveIntelligentSystemsLab/moving_object_detector.git src/moving_object_detector
RUN git clone https://github.com/ActiveIntelligentSystemsLab/disparity_visualize.git src/disparity_visualize
RUN git clone https://github.com/ActiveIntelligentSystemsLab/disparity_srv.git src/disparity_srv

# Install dependencies
RUN bash -c "apt-get update && \
             source /opt/ros/melodic/setup.bash && \
             rosdep install -i -y -r --from-paths src"

# Build
RUN bash -c "source /opt/ros/melodic/setup.bash && \
             catkin build"

# Replace entrypoint to load catkin_ws
RUN rm /ros_entrypoint.sh
COPY ros_entrypoint.sh /ros_entrypoint.sh
RUN chmod +x /ros_entrypoint.sh

# Load ROS environment at docker exec bash
RUN echo "source /opt/ros/melodic/setup.bash" >> /root/.bashrc
RUN echo "source /root/catkin_ws/devel/setup.bash" >> /root/.bashrc

# Install tools for development
RUN apt-get update && \
    apt-get install -y vim byobu
