FROM ros:melodic-perception

# Create a Catkin workspace
RUN mkdir -p /root/catkin_ws/src
WORKDIR /root/catkin_ws
RUN bash -c "source /opt/ros/melodic/setup.bash && \
             catkin_make"

# Download sources
RUN git clone https://aisl-serv6.aisl.cs.tut.ac.jp:20443/fujimoto/viso2_ros_pub_outlier.git src/viso2_ros
RUN git clone https://github.com/ActiveIntelligentSystemsLab/ros_optical_flow.git src/ros_optical_flow
RUN git clone https://aisl-serv6.aisl.cs.tut.ac.jp:20443/fujimoto/moving_object_detector.git src/moving_object_detector

# Install dependencies
RUN bash -c "apt-get update && \
             source /opt/ros/melodic/setup.bash && \
             rosdep install -i -y -r --from-paths src"

# Build
RUN bash -c "source /opt/ros/melodic/setup.bash && \
             source devel/setup.bash && \
             catkin_make"

# Replace entrypoint to load catkin_ws
RUN rm /ros_entrypoint.sh
COPY ros_entrypoint.sh /ros_entrypoint.sh
RUN chmod +x /ros_entrypoint.sh