version: "2.3"
services: 
  master:
    container_name: move_detect_master
    build: .
    command: roscore

  rqt:
    container_name: move_detect_rqt
    build: .
    depends_on:
      - master
    command: rqt 
    environment: 
      - ROS_HOSTNAME=move_detect_rqt
      - ROS_MASTER_URI=http://move_detect_master:11311
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - root:/root

  rviz:
    container_name: move_detect_rviz
    build: .
    depends_on:
      - master
    command: rviz
    runtime: nvidia
    environment: 
      - ROS_HOSTNAME=move_detect_rviz
      - ROS_MASTER_URI=http://move_detect_master:11311
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - root:/root

  terminal:
    container_name: move_detect_terminal
    build: .
    depends_on:
      - master
    command: lxterminal
    runtime: nvidia
    environment: 
      - ROS_HOSTNAME=move_detect_terminal
      - ROS_MASTER_URI=http://move_detect_master:11311
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - root:/root

volumes: 
  root:
